from cmu_112_graphics import *
import basic_graphics, time, random
import objects



# draw welcome page
class Welcome(object):
    def __init__(self, canvas):
        self.canvas = canvas
    
    def draw(self, canvas):
        
        boxX = 120
        boxY = 50

        # background
        canvas.create_rectangle(0, 0, self.width, self.height, 
                                fill='bisque')

        # name
        canvas.create_text(self.width//2, self.height//4, 
                           text='MESO',
                           font='Verdana 40 bold', 
                           fill='blue')

        # first button
        canvas.create_rectangle(self.width//2 - boxX, 
                                self.height//2 - 2*boxY,
                                self.width//2 + boxX,
                                self.height//2 - boxY,
                                fill=self.buttonColor1,
                                width=self.width1)
        
        canvas.create_text(self.width//2, self.height//2 - 1.5*boxY,
                           text='click to continue',
                           font='Verdana 16 bold', 
                           fill='black')
    
        # second button
        canvas.create_rectangle(self.width//2 - boxX, 
                                self.height//2 + boxY,
                                self.width//2 + boxX,
                                self.height//2 + 2*boxY,
                                fill=self.buttonColor2, 
                                width=self.width2)
            
        canvas.create_text(self.width//2, self.height//2 + 1.5*boxY,
                           text='click to view instructions',
                           font='Verdana 16 bold', 
                           fill='black')
    

# draw instructions page
class Instructs(object):

    def __init__(self, canvas):
        self.canvas = canvas
    
    def draw(self, canvas):
        margin = 20

        boxX = 120
        boxY = 50
        boxHeight = self.height - 6*margin

        backX = 50
        backY = 20
        backHeight = self.height - 3*margin

        font = 'Verdana 14'

        # background
        canvas.create_rectangle(0, 0, self.width, self.height, 
                                fill='bisque')

        # title
        canvas.create_text(self.width//2, self.app.margin+50, 
                           text='instructions', 
                           font='Verdana 22 bold', 
                           fill='blue')
        
        # instructions
        canvas.create_text(self.width//2, 150,
                           text='welcome to MESO!', font='Verdana 16 bold')
        
        canvas.create_text(self.width//4, 210,
                           text='create your map', font='Verdana 14 bold',
                           anchor=SW)

        canvas.create_text(self.width//4, 240,
                           text='to start off, you can choose whether you would like to set up your own map or', 
                           font=font, anchor=SW)
        canvas.create_text(self.width//4, 260,
                           text='use a map generated by the program', 
                           font=font, anchor=SW)
        canvas.create_text(self.width//4, 280,
                           text='if you choose to create your own map, click on the green space to place a lake', 
                           font=font, anchor=SW)
        canvas.create_text(self.width//4, 300,
                           text='mountains, tipis, and trees', 
                           font=font, anchor=SW)

        canvas.create_text(self.width//4, 330,
                           text='town residents', font='Verdana 14 bold',
                           anchor=SW)
        canvas.create_text(self.width//4, 360,
                           text='once you\'ve created your town, you will have civilians living in the tipis!', 
                           font=font, anchor=SW)
        canvas.create_text(self.width//4, 380,
                           text='watch as they interact with each other and their surroundings', 
                           font=font, anchor=SW)
        canvas.create_text(self.width//4, 400,
                           text='new civilians will arrive at the town every 100 years and', 
                           font=font, anchor=SW)
        canvas.create_text(self.width//4, 420,
                           text='collisions between residents will create a new one', 
                           font=font, anchor=SW)
        
        canvas.create_text(self.width//4, 450,
                           text='grow your town', font='Verdana 14 bold',
                           anchor=SW)
        canvas.create_text(self.width//4, 480,
                           text='click on the upgrades and new structures in the item bar to select and', 
                           font=font, anchor=SW)
        canvas.create_text(self.width//4, 500,
                           text='place these objects on the map to support your growing population', 
                           font=font, anchor=SW)


        




        # continue to game
        canvas.create_rectangle(self.width//2 - boxX, boxHeight - boxY,
                                self.width//2 + boxX, boxHeight,
                                fill=self.buttonColor5, width=self.width5)
        canvas.create_text(self.width//2, boxHeight - 0.5*boxY,
                           text='continue to game',
                           font='Verdana 18 bold', fill='black')

        # back button
        canvas.create_rectangle(self.width//2 - backX,
                                backHeight - backY,
                                self.width//2 + backX,
                                backHeight + backY,
                                fill=self.buttonColor3,
                                width=self.width3)

        canvas.create_text(self.width//2, backHeight,
                           text='back', font='Verdana 14 bold', 
                           fill='black')


# draw choosemode page
class Choose(object):
    def __init__(self, canvas):
        self.canvas = canvas

        
    def draw(self, canvas):
        boxX = 120
        boxY = 50
        backX = 50
        backY = 20
        backHeight = self.height - 3*self.margin

        # background
        canvas.create_rectangle(0, 0, self.width, self.height, 
                                fill='bisque')

        # name
        canvas.create_text(self.width//2, self.height//4, 
                           text='MESO',
                           font='Verdana 40 bold', 
                           fill='blue')

        # first button         
        canvas.create_rectangle(self.width//2 - boxX, 
                                self.height//2 - 2*boxY,
                                self.width//2 + boxX,
                                self.height//2 - boxY,
                                fill=self.buttonColor1, 
                                width=self.width1)
        
        canvas.create_text(self.width//2, self.height//2 - 1.5*boxY,
                           text='create your own map',
                           font='Verdana 16 bold', fill='black')

        # second button
        canvas.create_rectangle(self.width//2 - boxX, 
                                self.height//2 + boxY,
                                self.width//2 + boxX,
                                self.height//2 + 2*boxY,
                                fill=self.buttonColor2, 
                                width=self.width2)
            
        canvas.create_text(self.width//2, self.height//2 + 1.5*boxY,
                           text='auto-generate a map',
                           font='Verdana 16 bold', fill='black')
        
        # back button
        canvas.create_rectangle(self.width//2 - backX,
                                backHeight - backY,
                                self.width//2 + backX,
                                backHeight + backY,
                                fill=self.buttonColor3,
                                width=self.width3)

        canvas.create_text(self.width//2, backHeight,
                           text='back', font='Verdana 14 bold', fill='black')

                            
# draw basic game frame
class Frame(object):
    def __init__(self, canvas):
        self.canvas = canvas

    def draw(self, canvas):
        # game window
        canvas.create_rectangle(self.margin, 
                                self.margin, 
                                self.frameRightbound-self.margin/2, # 1125 - 10 
                                self.height - self.margin, # 800 - 20
                                fill='palegreen', width=2)
        # info window
        canvas.create_rectangle(self.frameRightbound+self.margin/2, 
                                self.margin,
                                self.width-self.margin, 
                                self.height-self.margin,
                                fill='mistyrose', width=2)

# draw info window
class Info(object):

    def __init__(self, canvas):
        self.canvas = canvas

    
    def draw(self, canvas, year, population):
        # game info
        canvas.create_text(self.infoMidX, 40, 
                           text=f'Year: {year}')
        canvas.create_text(self.infoMidX, 60,
                           text=f'Population: {(len(self.humans))**2}')
        canvas.create_text(self.infoMidX, 100,
                           text='Upgrades', font='Verdana 20 bold')

        # new tipi
        canvas.create_rectangle(self.infoMidX - self.buttonR,
                                200 - self.buttonR,
                                self.infoMidX + self.buttonR,
                                200 + self.buttonR,
                                fill='white', width=2, outline=self.outline1)
                                
        canvas.create_text(self.infoMidX, 230, text='Tipi', font='Verdana 12')
        canvas.create_polygon(self.infoMidX,            200-self.tipiR,
                              self.infoMidX+self.tipiR, 200+self.tipiR,
                              self.infoMidX-self.tipiR, 200+self.tipiR,
                              fill='burlywood', width=3,
                              outline='sienna')
        canvas.create_line(self.infoMidX, 200-self.tipiR, 
                           self.infoMidX+8, 200-self.tipiR-15, 
                           fill='sienna', width=3)
        canvas.create_line(self.infoMidX, 200-self.tipiR, 
                           self.infoMidX-8, 200-self.tipiR-15,
                           fill='sienna', width=3)

        # new house

        canvas.create_rectangle(self.infoMidX - self.buttonR,
                                350 - self.buttonR,
                                self.infoMidX + self.buttonR,
                                350 + self.buttonR,
                                fill='white', width=2, outline=self.outline2)

        canvas.create_text(self.infoMidX, 380, text='House', font='Verdana 12')

        canvas.create_polygon(self.infoMidX-self.houseR, 350-self.houseR,
                              self.infoMidX-self.houseR, 350+self.houseR,
                              self.infoMidX+self.houseR, 350+self.houseR,
                              self.infoMidX+self.houseR, 350-self.houseR,
                              self.infoMidX,        350-(2*self.houseR),
                              fill='silver', outline='black', width=2)


        # instructions button
        canvas.create_rectangle(self.infoMidX - 60, self.height - 80,
                                self.infoMidX + 60, self.height - 60,
                                fill=self.buttonColor4, width=self.width4)
        
        canvas.create_text(self.infoMidX, self.height - 70,
                           text='view instructions', font='Verdana 12')
        
        
        canvas.create_text(self.infoMidX, self.height - 40,
                           text='Press \'p\' to pause')


